### ISSUE TITLE
首页第一层的Mastering Bitcoin信息不太一致

### ISSUE THREAD

**Issue by yingang** [Blockchain-zju/blockchainer-roadmap#11]
原书有两个版本：
1. [Mastering Bitcoin : Unlocking Digital Cryptocurrencies](https://book.douban.com/subject/25855986/) 中文版叫：[区块链 : 通往资产数字化之路](https://book.douban.com/subject/30180770/)
1. [Mastering Bitcoin : Programming the Open Blockchain](https://book.douban.com/subject/27073959/) 中文版叫：[精通区块链编程 : 加密货币原理、方法和应用开发（原书第2版）](https://book.douban.com/subject/33476106/)

首页上用了第一版的中文名称和豆瓣介绍，但在线阅读又是第二版的翻译版本。

**Comment by DessertHeart** [comment]
感谢，将以第一版为准进行勘误
